# Default values for helmchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

fullnameOverride: hacktoberfest

image:
  repository: registry.net/hacktoberfest
  tag: latest
  pullPolicy: Always

deployment:
  annotations:
    k8s.hacktoberfest.com.br/db-oracle: "false"
    k8s.hacktoberfest.com.br/db-redis: "false"
    k8s.hacktoberfest.com.br/db-rabbitmq: "false"
    k8s.hacktoberfest.com.br/db-mongo: "false"
    k8s.hacktoberfest.com.br/occ: "false"

service:
  type: ClusterIP
  targetPort: 8080
  port: 80

ingress:
  enabled: false
  annotations:
    configuration.konghq.com: ingress-rewrite-path
  path: /hacktoberfest
  hosts:
    - hacktoberfest.com.br
  tls: []

persistence:
  enabled: "true"
  accessMode: "ReadWriteOnce"
  storageClass: "banana"
  size: "20Gi"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
